# Generated by Django 5.2.14 on 2026-09-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_listitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
