# Generated by Django 5.2.14 on 2026-09-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_listitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
